### ISSUE TITLE
Issues - Evan, Jared, Filora, Jean-Marc

### ISSUE THREAD

**Issue by Rankorrdagod** [sait-wbdv/fall-2021#1]
Schedule is hard to scroll through, maybe collapsible menu's for the weeks.

Library has a lot of links that maybe could be collapsed into categories to make them easier to find. Maybe separate windows to differentiate between content.

It would be awesome if embedded youtube links automatically opened in a new tab :)

**Comment by ashx3s** [comment]
Thank you for filing this. Issues 2, 3, and 4 have been created to address this ticket. This ticket will be closed, and work on those issues can be followed up in each of them.
