### ISSUE TITLE
Redesign library layout for easier searching

### ISSUE THREAD

**Issue by ashx3s** [sait-wbdv/fall-2021#3]
- based on [this issue](https://github.com/sait-wbdv/fall-2021/issues/1)

**Comment by acidtone** [comment]
@Rankorrdagod Completed a first pass of making the library more readable. Can we get a +1?

https://sait-wbdv.github.io/fall-2021/library/

**Comment by Rankorrdagod** [comment]
+1

**Comment by FesalBadday** [comment]
+1

**Comment by ashx3s** [comment]
Thank you, I'm going to mark this issue as closed. If there are any future ideas on revamping the library, we can do that as a separate issue.
